name: Push Docker Image
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set build arguments
        run: |
          echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
          echo "DOCKER_VERSION=$(node -p -e "require('./package.json').version")" >> $GITHUB_ENV

      - name: Print arguments
        run: |
          echo "Build Date: ${{ env.BUILD_DATE }}"
          echo "Version: ${{ env.DOCKER_VERSION }}"
          echo "Current branch name: $(git rev-parse --abbrev-ref HEAD)"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: d8:latest
          build-args: |
            DOCKER_BUILD_DATE=${{ env.BUILD_DATE }}
            DOCKER_VERSION=${{ env.DOCKER_VERSION }}
            
#     TODO: Add Test
